# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
#use_frameworks!

target 'Spika' do

pod 'AFNetworking'
pod 'JSONModel'
#pod 'SIOSocket', '~> 0.2.0'
#pod 'Socket.IO-Client-Swift'
pod 'SocketRocket', :git => 'https://github.com/facebook/SocketRocket.git'
pod 'SDWebImage'
pod 'UIAlertView+Blocks'

end

